services:

  postgres:
    image: postgres:15
    container_name: taskforge_postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-taskforge}
      POSTGRES_USER: ${POSTGRES_USERNAME:-taskforge_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-taskforge_password}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskforge-network


  mongo:
    image: mongo:7
    container_name: taskforge_mongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-taskforge_mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-taskforge_mongo_password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-taskforge_audit}
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - taskforge-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: taskforge_pgadmin
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@taskforge.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin_password}
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - taskforge-network


  mongo-express:
    image: mongo-express
    container_name: taskforge_mongo_express
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-taskforge_mongo_user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-taskforge_mongo_password}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD:-admin}
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - taskforge-network


  redis:
    image: redis:7-alpine
    container_name: taskforge_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-taskforge_redis_password}
    env_file:
      - .env
    volumes:
      - redis_data:/data
    networks:
      - taskforge-network
    command: redis-server --requirepass ${REDIS_PASSWORD:-taskforge_redis_password}


  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: taskforge_redis_insight
    restart: always
    ports:
      - "${REDIS_INSIGHT_PORT}:8001"
    environment:
      REDISINSIGHT_HOST: redis
      REDISINSIGHT_PORT: ${REDIS_PORT}
      REDISINSIGHT_PASSWORD: ${REDIS_PASSWORD:-taskforge_redis_password}
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - taskforge-network

  keycloack:
    image: quay.io/keycloak/keycloak:26.2
    container_name: taskforge_keycloack
    command:
      - start-dev
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: info
      KC_HOSTNAME: ${KC_HOSTNAME}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "${KEYCLOACK_PORT}:8080"
    depends_on:
      - postgres
    networks:
    -  taskforge-network

volumes:
  postgres_data:
  pgadmin_data:
  mongo_data:
  redis_data:

networks:
  taskforge-network:
    driver: bridge
